# Generated by Django 5.2 on 2025-06-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_tutoringcontactuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutoringContactUser',
        ),
    ]
