# Generated by Django 5.2 on 2025-07-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0004_contactuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
