# Generated by Django 5.2 on 2025-09-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0005_alter_contactuser_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamBoardCompletion',
        ),
    ]
