# Generated by Django 5.2 on 2025-10-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0006_delete_examboardcompletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUser',
        ),
    ]
