# Generated by Django 5.2 on 2025-07-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringcontactuser',
            name='tutor_name',
        ),
        migrations.AddField(
            model_name='tutoringcontactuser',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutoring.tutor'),
            preserve_default=False,
        ),
    ]
